[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model microk8s-localhost:test on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:927 unexpected facade UserSecretsDrain received from the controller
[33mWARNING [0m juju.client.connection:connection.py:927 unexpected facade UserSecretsManager received from the controller
[32mINFO    [0m integration.test_exporter:test_exporter.py:55 Deploying all the applications
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/grafana-agent-k8s-45
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-k8s-162
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-test-app-46
[32mINFO    [0m juju.model:model.py:2069 Deploying local:jammy/mysql-router-k8s-0
[32mINFO    [0m integration.test_exporter:test_exporter.py:94 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_exporter:test_exporter.py:100 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [executing] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-router-k8s/0 [idle] active: 
  mysql-test-app/0 [idle] active: 
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109b70>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45108c70>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109ae0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[32mINFO    [0m integration.test_exporter:test_exporter.py:134 Relating mysqlrouter with grafana agent
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aee500>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aef1c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45108d00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45108af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a451089d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45108f70>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a4510a230>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a451088e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109840>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45108040>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a451081f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45108c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109240>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a4510a950>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109e10>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109390>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109c00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45108400>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a4510a3e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45260fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a454f6cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a454f42b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a454f7940>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44d24400>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a454f50f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45109ba0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44d25150>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44d250c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44d24fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44d24910>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44d24bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44ef3b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44ef3bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44ef0520>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44ef0880>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aef100>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44ef3e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a4510a020>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aeff10>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aed570>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aee5f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aef130>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aed2a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aee7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a451094e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45272da0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45271ff0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45272e60>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aef280>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a44aee680>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45272980>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45270a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45273e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45273dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45273040>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a45271990>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics